spring:
  datasource:
    username: root
    password: root123
    url: jdbc:mysql://47.120.70.215:3306/fb?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver
mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml